# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Joey Chiao-Yin Hsiao
email: jcyhsiao@umich.edu
author: Joey Chiao-Yin Hsiao
description: > # "Write an awesome description for your new site here. 
copyright: 'Copyright &copy; 2017 Joey Hsiao. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
future: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: envelope
    url: mailto:jcyhsiao@umich.edu
  - title: linkedin
    url: https://www.linkedin.com/in/joeycyhsiao
  - title: facebook
    url: https://www.facebook.com/joey.hsiao


