# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://joeyhsiao.info
title: Joey Chiao-Yin Hsiao
email: jcyhsiao@umich.edu
author: Joey Chiao-Yin Hsiao, Joey Hsiao, Chiao-Yin Hsiao
description: "Joey Chiao-Yin Hsiao, a Ph.D. candidate at the School of Information, University of Michigan. Joey's research is focused on how location-based social applications, such as people-nearby applications and sharing economy applications, can support newcomers in adapting to a new environment."
copyright: 'Copyright &copy; 2020 Joey Hsiao. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
keywords:
  - Human-Computer Interaction
  - Computer-supported Cooperative Work
  - Social Computing
  - Location-based Social Media
  - People-nearby Application
  - Sharing Economy
  - Hybrid Community

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
future: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: envelope
    url: mailto:jcyhsiao@umich.edu
  - title: linkedin
    url: https://www.linkedin.com/in/joeycyhsiao
  - title: facebook
    url: https://www.facebook.com/joey.hsiao


